$(document).ready(function(){
    $(".searchdiv").focusin(function(){
        $(".searchdiv").removeClass("searchclass").addClass("searchclass2");
        console.log("p");
    });
    $(".searchdiv").focusout(function(){
        $(".searchdiv").removeClass("searchclass2").addClass("searchclass");
        console.log("p");
    });
});